export { Login } from './authetication'
export * from './students'
export * from './professors'
export * from './teams'
export * from './boxes'
export {default as Home} from './home/Home'
export {default as Profile} from './profile/Profile'
export {default as NotFound} from './notFound/NotFound'
export {default as PublicPage} from './publicPage/PublicPage'
export {default as Dashboard} from './dashboard/Dashboard'